SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

INSERT INTO `content_items` (
  `type`,
  `title`,
  `slug`,
  `excerpt`,
  `content`,
  `featured_image`,
  `payload_json`,
  `meta_title`,
  `meta_description`,
  `status`,
  `published_at`,
  `starts_at`,
  `ends_at`,
  `created_by`,
  `updated_by`
) VALUES
(
  'services',
  'Corporate Website Platform',
  'corporate-website-platform',
  'Schaalbare corporate website met governance, security en duidelijke contentflows.',
  'Voor middelgrote en grote organisaties bouwen we een corporate websiteplatform met rollen, workflows en doorontwikkeling.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('cta_label', 'Plan strategische sessie', 'cta_url', '/contact', 'price_hint', 'Vanaf EUR 12.500'),
  'Corporate Website Platform | Fundamental CMS',
  'Enterprise-ready corporate website met beheer en schaalbaarheid.',
  'published',
  NOW() - INTERVAL 12 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'services',
  'B2B Lead Generation Website',
  'b2b-lead-generation-website',
  'Website gericht op leadgeneratie met landingpages, formulieren en dashboards.',
  'We combineren duidelijke proposities, CRO en meetbare flows voor meer MQLs en SQLs.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('cta_label', 'Bekijk aanpak', 'cta_url', '/werkwijze', 'price_hint', 'Vanaf EUR 7.500'),
  'B2B Lead Generation Website | Fundamental CMS',
  'Meer kwalitatieve leads met een conversiegerichte B2B website.',
  'published',
  NOW() - INTERVAL 11 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'services',
  'Employer Branding Website',
  'employer-branding-website',
  'Sterke werkenbij-site met vacatureflows, cultuurverhalen en sollicitatiepaden.',
  'Voor HR- en recruitmentteams bouwen we employer branding websites die kandidaten activeren.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('cta_label', 'Plan intake HR', 'cta_url', '/contact', 'price_hint', 'Vanaf EUR 6.900'),
  'Employer Branding Website | Fundamental CMS',
  'Werkenbij-website voor betere instroom van kandidaten.',
  'published',
  NOW() - INTERVAL 10 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'portfolio',
  'Project: IndustrieGroup Corporate Relaunch',
  'project-industriegroup-corporate-relaunch',
  'Volledige corporate relaunch voor internationale industriële groep.',
  'Nieuwe informatiearchitectuur, meertalige content en duidelijke investor-relations secties.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('client_name', 'IndustrieGroup', 'result_metric', '+52% meer organisch verkeer', 'quote', 'Onze teams publiceren nu sneller in 4 talen.'),
  'Case IndustrieGroup | Fundamental CMS',
  'Corporate relaunch met meetbare groei in verkeer en leadkwaliteit.',
  'published',
  NOW() - INTERVAL 9 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'portfolio',
  'Project: FinCore B2B Leadmachine',
  'project-fincore-b2b-leadmachine',
  'B2B website met campagne-landingpages en marketing automation koppelingen.',
  'Gerichte paginaflows voor sectoren en use-cases zorgden voor hogere demo-aanvragen.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('client_name', 'FinCore', 'result_metric', '+41% demo aanvragen', 'quote', 'Marketing en sales werken nu vanuit dezelfde contentstructuur.'),
  'Case FinCore | Fundamental CMS',
  'Leadgedreven B2B website voor groei in demo-aanvragen.',
  'published',
  NOW() - INTERVAL 8 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'portfolio',
  'Project: NovaCare Employer Site',
  'project-novacare-employer-site',
  'Employer branding platform met regionale vacaturepagina\'s en teamverhalen.',
  'Met persona-gedreven content is de sollicitatieconversie sterk verbeterd.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('client_name', 'NovaCare', 'result_metric', '+33% sollicitaties', 'quote', 'De werkenbij-site sluit eindelijk aan op onze cultuur.'),
  'Case NovaCare | Fundamental CMS',
  'Employer branding case met meer sollicitaties en betere kandidaatmatch.',
  'published',
  NOW() - INTERVAL 7 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'testimonials',
  'Review van Delta Logistics',
  'review-delta-logistics',
  'Strakke samenwerking met duidelijke planning en veel inhoudelijke scherpte.',
  'Het projectteam leverde niet alleen een mooie site, maar vooral een beter werkproces voor contentteams.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('client_name', 'Delta Logistics', 'client_role', 'Head of Marketing', 'rating', '5'),
  'Review Delta Logistics | Fundamental CMS',
  'Klantreview over corporate website traject.',
  'published',
  NOW() - INTERVAL 6 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'testimonials',
  'Review van ArgoTech',
  'review-argotech',
  'Van losse landingspagina\'s naar een consistente website met duidelijke structuur.',
  'De nieuwe setup maakt campagnes sneller en geeft sales betere content om mee te werken.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('client_name', 'ArgoTech', 'client_role', 'Commercial Director', 'rating', '5'),
  'Review ArgoTech | Fundamental CMS',
  'Ervaring van ArgoTech met replatforming en groei.',
  'published',
  NOW() - INTERVAL 5 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'faq',
  'Kunnen jullie migreren vanaf WordPress?',
  'kunnen-jullie-migreren-vanaf-wordpress',
  'Ja, we migreren content, redirects en metadata gefaseerd zonder SEO-verlies.',
  'We starten met een content-audit en migratieplan zodat livegang gecontroleerd verloopt.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('question', 'Kunnen jullie migreren vanaf WordPress?', 'topic', 'Migratie', 'answer', 'Ja, inclusief contentmapping, redirects en SEO-validatie.'),
  'FAQ Migratie WordPress | Fundamental CMS',
  'Antwoord op migratievraag voor corporate websites.',
  'published',
  NOW() - INTERVAL 4 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'faq',
  'Hoe zit het met meertalige websites?',
  'hoe-zit-het-met-meertalige-websites',
  'We ondersteunen meertalige structuren met centrale governance en lokale redactie.',
  'Per taal kunnen teams werken met eigen workflows, publicatieregels en reviewstappen.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('question', 'Hoe zit het met meertalige websites?', 'topic', 'Meertalig', 'answer', 'Volledige ondersteuning voor meertalige content en governance.'),
  'FAQ Meertalige websites | Fundamental CMS',
  'Uitleg over meertalige corporate websites.',
  'published',
  NOW() - INTERVAL 3 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'downloads',
  'Template: Corporate Website Contentmodel',
  'template-corporate-website-contentmodel',
  'Praktisch template voor paginatypen, velden en redactionele afspraken.',
  'Gebruik dit model om contentteams, marketing en IT op dezelfde structuur te krijgen.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('file_url', '/uploads/media/2026/03/image-4-20260306202030-591ac330.png', 'file_type', 'PDF', 'file_size', '2.1 MB'),
  'Template contentmodel | Fundamental CMS',
  'Download template voor corporate contentarchitectuur.',
  'published',
  NOW() - INTERVAL 2 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'knowledge_base',
  'Hoe richt ik dienstpagina\'s in voor conversie?',
  'hoe-richt-ik-dienstpaginas-in-voor-conversie',
  'Checklist voor opbouw van dienstpagina\'s met duidelijke CTA en bewijsvoering.',
  'Van headline tot FAQ: zo maak je dienstpagina\'s die beter converteren voor B2B.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('topic', 'Services', 'difficulty', 'Intermediate', 'support_url', '/support'),
  'Kennisbank dienstpagina\'s | Fundamental CMS',
  'Handleiding voor conversiegerichte dienstpagina\'s.',
  'published',
  NOW() - INTERVAL 1 DAY,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'partners',
  'Partner: Insight Analytics',
  'partner-insight-analytics',
  'Datapartner voor dashboarding, KPI-frameworks en marketingattributie.',
  'Samen helpen we bedrijven betere keuzes maken op basis van websiteprestaties.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('website_url', 'https://example.com', 'logo_url', '/uploads/media/2026/03/image-4-20260306202030-591ac330.png', 'partnership_type', 'Data partner'),
  'Partner Insight Analytics | Fundamental CMS',
  'Meer over onze datapartner Insight Analytics.',
  'published',
  NOW() - INTERVAL 13 HOUR,
  NULL,
  NULL,
  NULL,
  NULL
),
(
  'jobs',
  'Content Strategist',
  'content-strategist',
  'Help bedrijven met informatiearchitectuur, messaging en contentgovernance.',
  'Je werkt met marketing- en communicatieteams aan schaalbare websitestructuren.',
  '/uploads/media/2026/03/image-4-20260306202030-591ac330.png',
  JSON_OBJECT('location', 'Utrecht / hybride', 'employment_type', '32-40 uur', 'apply_url', '/contact'),
  'Vacature Content Strategist | Fundamental CMS',
  'Word Content Strategist binnen ons digital team.',
  'published',
  NOW() - INTERVAL 12 HOUR,
  NOW() - INTERVAL 12 HOUR,
  NOW() + INTERVAL 60 DAY,
  NULL,
  NULL
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `excerpt` = VALUES(`excerpt`),
  `content` = VALUES(`content`),
  `featured_image` = VALUES(`featured_image`),
  `payload_json` = VALUES(`payload_json`),
  `meta_title` = VALUES(`meta_title`),
  `meta_description` = VALUES(`meta_description`),
  `status` = VALUES(`status`),
  `published_at` = VALUES(`published_at`),
  `starts_at` = VALUES(`starts_at`),
  `ends_at` = VALUES(`ends_at`),
  `updated_at` = NOW();

INSERT INTO `pages` (
  `title`,
  `slug`,
  `excerpt`,
  `content`,
  `builder_json`,
  `template`,
  `page_type`,
  `meta_title`,
  `meta_description`,
  `status`,
  `published_at`
) VALUES
(
  'Voor bedrijven',
  'voor-bedrijven',
  'Websites voor B2B en corporate organisaties met focus op groei en beheerbaarheid.',
  'Wij bouwen bedrijfswebsites die marketing, sales en communicatie verbinden in een schaalbaar platform.',
  '[{"type":"hero","data":{"title":"Websites voor bedrijven die willen groeien","subtitle":"Van corporate platform tot leadgeneratie: wij bouwen een fundament dat werkt.","cta_label":"Plan een gesprek","cta_url":"/contact"}},{"type":"columns","data":{"columns":[{"heading":"Corporate","content":"Governance, meertalig en stakeholder-proof."},{"heading":"B2B","content":"Leadflows, landingspagina\'s en conversion optimalisatie."},{"heading":"Recruitment","content":"Sterke werkenbij-site met candidate journeys."}]}},{"type":"cta","data":{"label":"Bekijk cases","url":"/portfolio","style":"primary"}}]',
  'landing',
  'landing_page',
  'Voor bedrijven | Fundamental CMS',
  'Bedrijfswebsites voor B2B, corporate en recruitment.',
  'published',
  NOW()
),
(
  'Branches',
  'branches',
  'Voorbeelden en aanpak per branche.',
  'Wij ondersteunen organisaties in industrie, fintech, zorg, logistiek en zakelijke dienstverlening.',
  '[{"type":"text","data":{"content":"Per branche werken we met specifieke contentmodellen, compliance-eisen en doelgroepflows."}},{"type":"cta","data":{"label":"Neem contact op","url":"/contact","style":"secondary"}}]',
  'default',
  'basic_page',
  'Branches | Fundamental CMS',
  'Onze website-oplossingen per branche.',
  'published',
  NOW()
)
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `excerpt` = VALUES(`excerpt`),
  `content` = VALUES(`content`),
  `builder_json` = VALUES(`builder_json`),
  `template` = VALUES(`template`),
  `page_type` = VALUES(`page_type`),
  `meta_title` = VALUES(`meta_title`),
  `meta_description` = VALUES(`meta_description`),
  `status` = VALUES(`status`),
  `published_at` = VALUES(`published_at`),
  `updated_at` = NOW();

INSERT INTO `menu_items` (`parent_id`, `location`, `label`, `url`, `sort_order`, `is_active`, `created_at`, `updated_at`)
SELECT NULL, 'main', 'Voor bedrijven', '/voor-bedrijven', 32, 1, NOW(), NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM `menu_items` WHERE `location` = 'main' AND `url` = '/voor-bedrijven'
);

INSERT INTO `menu_items` (`parent_id`, `location`, `label`, `url`, `sort_order`, `is_active`, `created_at`, `updated_at`)
SELECT NULL, 'main', 'Branches', '/branches', 34, 1, NOW(), NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM `menu_items` WHERE `location` = 'main' AND `url` = '/branches'
);

COMMIT;
